"""EDC nomenclatures: code → French label mappings.

PORTED FROM: files_late_fee/src/deces_risk/datasources/edc/nomenclatures.py
PORTED ON:   2026-09-18
DIVERGENCE:  none (verbatim) + NOMENCLATURES registry appended.

- ``TYPE_EVT`` / ``SOUS_TYPE_EVT``: ESDEVENEMENT.TYPEEVT / SOUSTYPEEVT.
  For subtypes '1' and '3', a composite key ``"<soustype>.<critere>"`` is
  used when CRITEREEVT2 is '1' or '2' (e.g. ``"1.1"`` = Arrivée courrier).
- ``SOUS_TYPE_ALERTE``: subtype labels when TYPEEVT == '5' (Alerte).
- ``TYPE_INTERCALAIRE``: '1'=Assuré, '2'=Bénéficiaire, '6'=Bénéficiaire présumé…
- ``MOTIF_FT`` / ``MOTIF_ATTENTE``: closure motives (fin de traitement / attente).
- ``INTERLOCUTEUR``: nature of the interlocutor (notaire, enquêteur…).
"""


TYPE_EVT = {
    "1": "Courrier (entrant ou sortant)",
    "2": "Echange partenaire", # Tres rare
    "3": "Communication",
    "4": "Appel Système de Gestion", # Tres rare
    "5": "Alerte",
    "6": "Evénement standard"
}

# Pour 1 , 3 et 6
SOUS_TYPE_EVT = {
    '1': 'Courrier',
    '1.1': 'Arrivée courrier',
    '1.2': 'Communication sortante',
    '2': 'Retour pièces',
    '3': 'Communication téléphonique',
    '3.1': 'Réception com. téléphonique',
    '3.2': 'Communication sortante',
    '4': 'Ouverture du dossier',
    '5': 'Rejet financier  - motif décès',
    '6': '1ère Information venant du partenaire Poste',
    '7': 'Information à destination du partenaire Poste',
    '8': 'Information à destination du partenaire Poste',
    '9': 'Information à destination du partenaire Poste',
    '10': 'Recensement du courrier',
    '11': 'Rattachement de pièce',
    '12': 'Définition liste type des pièces',
    '13': 'Demande de pièces par e-Décès',
    '14': 'Première relance automatique de demande de pièces',
    '15': 'Seconde relance automatique de demande de pièces',
    '16': 'Relance manuelle de demande de pièces',
    '17': 'Contrôler la complétude',
    '18': "Demande d'archive",
    '19': 'Modification de clause bénéficiaire',
    '20': 'Autorisation de saisie du dossier réel',
    '21': 'Saisie du décès présumé',
    '22': 'Saisie du décès réel',
    '23': 'Validation des affaires',
    '24': 'Invalidation totale ou partielle des affaires',
    '25': 'Recettes à traiter',
    '26': 'Prestation à rembourser à la succession',
    '27': 'Remboursement recette ou prestation à la succession',
    '28': 'Remboursement recette ou prestation à la succession',
    '29': 'Modification des données chiffrées',
    '30': 'Clôture suite à RIE',
    '31': 'Clôture du dossier',
    '32': "Qualification d'un bénéficiaire",
    '33': 'Saisie des quotités',
    '34': "Ordonnancement d'une prestation",
    '35': 'Emploi des fonds',
    '36': 'Modification des données',
    '37': "Ajournement d'une alerte ou d'une instance",
    '38': 'Changement chef de file',
    '39': 'Dessaisissement ponctuel',
    '40': 'Evénement sur dossier autres réseaux',
    '41': 'Réaction client',
    '42': "Déqualification d'un bénéficiaire",
    '43': "Suivi d'activité",
    '44': 'Client multi-réseaux',
    '45': 'Suppression du attachement de pièce',
    '46': 'Suppression de pièce',
    '47': 'Information temporaire à destination du partenaire Poste',
    '48': 'Information automatique à destination du partenaire Poste',
    '49': 'Récupération du dossier SGP',
    '50': 'Compléter portefeuille',
    '51': 'Annulation de dossier',
    '52': "Annulation d'une demande de pièces",
    '53': "Modification des coordonnées d'un événement",
    '54': 'Demande information',
    '55': 'Indus',
    '56': 'Réactivation dossier',
    '57': 'Annulation décès réel',
    '58': 'Enrichissement du dossier',
    '59': 'Communication des clauses bénéficiaires',
    '60': 'Archivage dossier',
    '61': 'Modification des données Doc.A',
    '62': 'Lettre notaire',
    '63': 'Information initiale au partenaire',
    '64': 'Information demande de pièces au partenaire',
    '65': 'Information complémentaire au partenaire',
    '66': 'Information bénéficiaire au partenaire',
    '67': 'Information prêt à payer au partenaire',
    '68': 'Création dossier défunt partenaire',
    '69': 'Initialisation dossier partenaire',
    '70': 'Création dossier bénéficiaire partenaire',
    '71': 'Demande de pièces pour bénéficiaire partenaire',
    '72': 'Suppression dossier partenaire',
    '73': 'Courrier PND',
    '74': 'Dossier sensible',
    '75': 'Courrier notaire avec dévolution successorale',
    '76': 'Courrier notaire sans dévolution successorale',
    '77': "Annulation d'un courrier",
    '78': "1ère information provenant de l'INSEE",
    '79': 'AGIRA',
    'M20': 'Fichier Séralys',
    '80': 'Création Interlocuteur',
    '81': 'Intérêts de retard',
    '82': 'Paiement intérêts de retard',
    '83': 'Validation du paiement',
    '84': 'Clôture manuelle des intérêts de retard',
    '85': 'Annulation du paiement',
    '86': 'Demande de RIB/RICE',
    '87': 'Courrier paiement des intérets de retard',
    '88': 'Demandeur non bénéficiaire',
    '89': 'Clôture automatique des intérets de retard',
    '90': 'Information partenaire CE',
    '91': 'Supprimer contrat du portefeuille',
    '92': "Synchro au fil de l'eau",
    '93': 'Synchronisation du numéro de dossier',
    '94': 'Contrat sans prestation',
    '95': 'Contrat sans dénouement',
    '96': 'Annulation décision contrat',
    '97': "Annulation d'un ordonnancement",
    '98': "Annulation d'un réemploi",
    '99': 'Ajout coordonnées bancaires',
    'A1': 'Validation des affaires',
    'A2': 'Saisie informations contrat',
    'A3': 'Retour dossier partenaire',
    'A4': 'Prise en charge Partenaire',
    'A5': 'Prise en charge CNP',
    'A6': 'Dessaissement partenaire',
    'A7': 'Réaffectation responsable',
    'A8': 'Traitement/création automatique',
    'A9': '1ère information provenant du batch DC auto (homonymes autres réseaux)',
    'A10': "Modification de l'état du RIB",
    'B0': 'Alerte délai',
    'B1': 'Alerte reprise',
    'B2': "Courrier d'attente",
    'B3': 'Acceptation Prise en charge partenaire',
    'B4': 'Refus de prise en charge Partenaire',
    'B5': 'Absence PEC partenaire',
    'B6': 'Délai constitution dossier défunt dépassé - Prise en charge CNP',
    'B7': 'Dessaisissement dossier défunt en cours de constitution - Envoi CNP',
    'B8': 'Délai constitution dossier défunt dépassé - Envoi CNP',
    'B9': 'Mise à jour coordonnées partenaire',
    'C0': 'Demande de pièces partenaire',
    'C1': 'Réception de pièces partenaire',
    'C2': 'Annulation réception de pièces partenaire',
    'C3': 'Envoi dossier BO Partenaire pour contrôle',
    'C4': 'Demande de prestations Partenaire',
    'C5': 'Non conformité partenaire',
    'C6': 'Fin constitution partenaire',
    'C7': 'Ouverture dossier partenaire',
    'C8': "1ère information provenant de l'INSEE",
    'C9': 'Acceptation dénouement partenaire',
    'D0': 'Information création dossier Web vers partenaire',
    'D1': 'Echec dénouement partenaire',
    'D2': 'Echec dénouement partenaire',
    'D3': 'Refus dénouement partenaire',
    'D4': 'Courrier paiement bénéficiaire',
    'D5': 'Courrier paiement complémentaire',
    'D6': 'Courrier paiement tiers',
    'D7': 'Flux partenaire',
    'D8': 'Annulation bénéficiaire partenaire',
    'D9': 'Courrier paiement bénéficiaire simplifié',
    'E0': 'Enregistrement date de décès INSEE',
    'E1': 'dossier Yvoire',
    'E2': 'Divergence date de décès',
    'E3': 'Déclenchement automatique du décès réél',
    'E6': 'Bénéficiaire règlé',
    'BRP': 'Bénéficiaire règlé partiellement',
    'E7': 'demande dématérialisation partenaire',
    'E8': 'Retour agence partenaire',
    'E9': 'Prise en charge CNP suite à absence de constitution',
    'E10': 'Enregistrement date de décès AGIRA',
    'E11': 'Déclenchement automatique du décès réél agira',
    'E12': 'Divergence date de décès',
    'E13': 'Enregistrement date de décès SERALYS',
    'E14': 'Déclenchement automatique du décès réél séralys',
    'E15': 'Divergence date de décès',
    'F0': 'Coordonnées bancaires externes',
    'F1': 'Rafraichir portefeuille',
    'F2': 'piece IDD',
    'F8': 'Complétude des clauses',
    'F9': 'Acceptation partielle',
    'DPC': 'Demande de pièces partenaire avec courrier',
    'N2': 'Annulation demande de pièces partenaire avec courrier',
    'H0': 'Invalidation',
    'H1': 'Bénéficiaire règlé',
    'H2': "Rapport d'enquête positif",
    'H3': "Rapport d'enquête négatif",
    'H4': 'Identification personne morale',
    'H5': 'Clauses complètes',
    'H6': 'Prise en charge Partenaire par défaut',
    'H8': 'Evenement IDD',
    'I1': 'Demande de refus de prise en charge',
    'I2': 'MAJ dossier bénéficiaire partenaire',
    'I3': 'Demande dessaisissement dossier défunt en cours de constitution',
    'I4': 'Refus dessaisissement dossier défunt en cours de constitution',
    'I5': 'Dossier bénéficiaire conforme Partenaire',
    'I6': 'Dossier bénéficiaire non conforme à traiter Agence Partenaire',
    'I7': 'Dossier bénéficiaire non conforme à traiter BO Partenaire',
    'I8': 'Propagation pièces dossier bénéficiaire partenaire',
    'J1': 'Annulation demande de pièces Partenaire',
    'J2': 'MAJ rattachement pièces reçues Partenaire',
    'J3': 'Suppression dossier bénéficiaire partenaire',
    'J4': 'Demande dessaisissement dossier bénéficiaire en cours de constitution',
    'J5': 'Refus dessaisissement dossier bénéficiaire en cours de constitution',
    'J6': 'Dessaisissement dossier bénéficiaire en cours de constitution-Envoi CNP',
    'J7': 'Traitement dossier bénéficiaire par le BO Partenaire',
    'J8': 'Recherche Partenaire bénéficiaire(s)',
    'J9': 'Identification bénéficiaire partenaire en attente de constitution',
    'K1': 'Modification bénéficiaire partenaire en attente de constitution',
    'K2': 'Suppression bénéficiaire partenaire en attente de constitution',
    'K3': 'Prise de rendez-vous Partenaire bénéficiaire en attente de constitution',
    'K4': 'Traitement dossier défunt par le BO Partenaire',
    'K5': 'Clôture dossier fin traitement',
    'K6': 'Réactivé (fin de traitement)',
    'M21': 'Demande de fin traitement annulée',
    'M22': 'Demande de fin traitement',
    'M23': 'Demande de fin traitement approuvée',
    'M24': 'Demande de mise en attente annulée',
    'M25': 'Demande de mise en attente',
    'M26': 'Demande de mise en attente approuvée',
    'K7': 'Dossier manuel partenaire',
    'K8': 'Demande de prise en charge Partenaire',
    'K9': 'Fin de traitement non-conformité Partenaire',
    'K11': 'Gestion de la conformité',
    'K12': 'Part calculée suite enregistrement critères de répartition (Questions/Réponses)',
    'K13': 'Enregistrement critères de répartition (Questions/Réponses)',
    'K14': "Maj état d'analyse partenaire dossier",
    'K15': 'Prise en charge par un intermédiaire',
    'L1': 'Dossier en cours de transfert CDC',
    'L2': 'Transfert CDC impossible',
    'L3': 'Courrier info transfert CDC',
    'L4': 'Courrier info transfert CDC non requis',
    'L5': 'Annulation quotité',
    'L6': 'Dossier transféré CDC',
    'L7': 'Dossier transféré partiellement CDC',
    'L8': 'Annulation transfert CDC',
    'L9': "Arrêt des relances 'demande de pièces'",
    'L10': "Transfert Responsabilité d'instruction dossier",
    'LN1': 'LAD Lettre notaire OK',
    'LN2': 'LAD Lettre notaire KO',
    'M1': 'Modification demande partenaire',
    'M2': 'Création dossier bénéficiaire web',
    'M3': 'Fin constitution dossier web',
    'M4': 'Demande enquête',
    'M5': 'Dossier annulé par batch edc',
    'M6': 'Dossier annulé par fusion',
    'M7': "Annulation d'une alerte",
    'M8': 'Clôture dossier mise en attente',
    'M9': 'Réactivé (mise en attente)',
    'M10': 'Connexion bénéficiaire à ES BPCE',
    'M11': 'Fin de constitution ES BPCE',
    'M12': 'Création bénéficiaire dans ES BPCE',
    'M19': "Transmission nouveau bénéficiaire à l'ES BPCE",
    'M14': 'Instruction manuelle',
    'M15': 'Erreur sur les traitements automatiques liés au paiement',
    'M16': 'Présence du reliquat à payer en manuel',
    'M17': 'Présence des contrats non gérés',
    'M18': 'Présence des contrats non éligibles',
    'M30': 'Paiement autorisé par LCBFT',
    'M31': 'Paiement refusé par LCBFT',
    'M32': 'Paiement autorisé par défaut par LCBFT',
    'M33': 'Paiement annulé avant retour LCBFT',
    'M34': 'Paiement en attente de décision LCBFT',
    'M40': 'Gestion des Pièces',
    'M41': 'Propagation de document sortante',
    'M42': 'Propagation de document entrante',
    'M43': 'Gestion des contrats et qualités',
    'MA1': 'Notification mail',
    'N1': 'Délégation du dossier vers LBP',
    'N3': 'Dossier relationné',
    'N4': 'Affectation centre financier',
    'N5': 'Demandeur partiellement non bénéficiaire',
    'N6': 'Courrier garantie décès accidentel non couverte',
    'E4': 'Validation automatique',
    'E5': 'Demande de validation',
    'F4': 'Alerte au moins un contrat non décédé',
    'F6': 'Alerte problème décès réel',
    'F3': 'Alerte aucun contrat en décès réel',
    'F5': 'Alerte problème affectation responsable',
    'DY': 'Affectation dossier à prendre en charge',
    'EQ1': "Emission Demande d'Enquête",
    'EQ2': 'Emission Contre Enquête',
    'EQ3': 'Affectation à Enquêteur',
    'EQ4': 'Retour Enquête',
    'EQ5': 'Retour Contre Enquête',
    'EQ6': 'Affectation Contre Enquête à Enquêteur',
    'EQ7': "Annulation demande d'enquête",
    'EQ8': 'Annulation contre enquête',
    'FPP': 'Fin de constitution partielle partenaire',
    'FTP': 'Fin de constitution totale partenaire',
    'FPW': 'Fin de constitution partielle',
    'ZZ': 'Evenement Technique',
    'W1': 'Alerte absence de bénéficiaire ou interlocuteur créé pour clause bénéficiaire libre',
    'W2': 'Alerte absence demande de pièces',
    'W3': 'Alerte absence fin de traitement',
    'W4': 'Alerte demande mairie non aboutie',
    'W5': "Alerte dossier en attente depuis plus d'1 an",
    'W6': 'Alerte dossier inactif',
    'W7': 'Alerte dossier sans bénéficiaire à 120 jours',
    'W8': 'Alerte désarchivage clause bénéficiaire',
    'W9': 'Alerte fin de traitement',
    'W10': 'Alerte incohérence date décès',
    'W11': 'Alerte modifier montant',
    'W12': 'Alerte non réponse mairies',
    'W13': 'Alerte paiement sur dossier lié',
    'W14': "Alerte présence d'une recette : délai d'impayé de 21 jours à respecter",
    'W15': "Alerte risque d'intérêts de retard avant paiement",
    'W16': 'Alerte saisie décès réel non réalisé',
    'W19': 'Alerte BPCE Dessaisissement',
    'K10': 'Modification date de souscription',
    'DM1': 'Création nouveau démembrement',
    'DM2': 'Annulation démembrement',
    'RP1': "Réception logique d'un document",
    'RP2': "Réception physique d'un document",
    'RP3': "Réception virtuelle d'un document",
    'RP4': "Réception manuelle d'un document",
    'RM': "Rapprochement manuel d'un document"
}

SOUS_TYPE_ALERTE = {
    '1': 'Créer un événement',
    '2': 'Annuler dossier',
    '3': 'Recenser les pièces',
    '4': 'Rattacher les pièces',
    '5': 'Traiter les événements orphelins',
    '6': 'Bloquer en décès présumé',
    '7': 'Créer / enrichir dossier',
    '8': 'Compléter le portefeuille',
    '10': 'Désarchivage clause bénéficiaire',
    '11': 'Autoriser saisie décès réel',
    '12': 'Saisir le décès réel',
    '13': 'Modifier montant',
    '14': 'Définir pièces nécessaires',
    '15': 'Demander les pièces',
    '17': 'Informer le partenaire',
    '18': 'Qualifier un bénéficiaire',
    '19': 'Saisir les quotités',
    '20': 'Ordonnancer une prestation',
    '21': 'Employer les fonds',
    '22': 'Valider les dossiers',
    '23': 'Annuler bénéficiaire',
    '24': "Ajourner l'alerte",
    '25': 'Modifier les coordonnées',
    '27': "Changer l'unité chef de file",
    '28': 'Se dessaisir ponctuellement',
    '29': 'Consulter un dossier décès',
    '30': 'Consulter les tableaux de bord',
    '31': 'Consulter les validation',
    '32': 'Valider les ordonnancements et les paiements',
    '33': 'Modifier les coordonnées',
    '34': 'Modifier les coordonnées',
    '35': 'Modifier les coordonnées',
    '36': 'Modifier les coordonnées',
    '37': 'Modifier les coordonnées',
    '39': 'Annuler demande de pièces',
    '41': 'Annuler bénéficiaire',
    '42': 'Annuler bénéficiaire',
    '44': 'Client multi-reseaux',
    '45': 'Evénement autre réseau',
    '46': 'Annuler décès via C70',
    '47': 'Annuler décès via VDA',
    '48': 'Contrôler la complétude',
    '49': 'Demande de pièces multiples',
    '50': 'Informer partenaire Trésor',
    '51': 'Payer les intérêts de retard',
    '52': 'Valider le paiement des intérêts de retard',
    '53': 'Demande RIB en cours',
    '54': 'Contrat Sans Prestation',
    '55': 'Contrat Sans Dénouement',
    '56': 'Saisir Informations contrat',
    '57': 'BPCE Instruction CNP',
    '64': 'BPCE Délai de constitution dépassé',
    '65': 'BPCE Absence instruction partenaire',
    '90': 'Demander doc.A au CRSF',
    '92': "Déssaisissement ponctuel d'un dossier",
    '93': 'Communication téléphonique avec délai',
    '94': 'Créer événement sortant interlocuteur',
    '95': 'Communication téléphonique sans délai',
    '96': 'Demande de pièces multiples',
    '97': "Arrivée d'un document A",
    '98': "Réception d'un rejet financier",
    '99': '',
    '100': 'Création dossier PUMA',
    '101': 'Demande de fin traitement',
    '102': 'Demande de mise en attente',
    'A1': 'Pb lors de la création automatique du dossier',
    'A3': 'Problème aucun contrat en décès réel lors création automatique du dossier',
    'A4': 'Problème au moins un contrat sans décès réel lors création automatique du dossier',
    'A5': "Problème décès réel lors de la création automatique du dossier sur l'Assuré",
    'A8': "Le partenaire s'est dessaisi du dossier",
    'A9': 'Valeur UC inconnue attente de cotation',
    'A10': "Délai d'attente de cotation dépassé",
    'A11': 'Incohérence date de décès',
    'B1': 'Paiement sur dossier lié',
    'B2': "Présence d'une recette : délai d'impayé de 21 jours à respecter",
    'B3': 'Dossier inactif',
    'B4': "Risque d'intérêts de retard avant paiement",
    'B6': 'Absence demande de pièces',
    'B7': 'Dossier sans bénéficiaire à 120 jours',
    'B8': 'Saisie décès réel non réalisé',
    'B9': 'Fin de traitement',
    'B10': 'BPCE PEC',
    'B11': 'BPCE Dessaisissement',
    'B13': 'Absence de bénéficiaire ou interlocuteur créé pour clause bénéficiaire libre',
    'B14': 'Dénouement informations web bénéficiaire',
    'B15': "Dossier en attente depuis plus d'1 an",
    'B16': 'Demande mairie non aboutie',
    'B17': 'Non réponse mairies',
    'B18': 'Paiement annulé LCB-FT',
    'B12': 'Absence fin de traitement',
    'B19': 'Présence de compte(s) capi actif(s)'
}

TYPE_INTERCALAIRE = {
    "1": "Assuré",
    "2": "Bénéficiaire",
    "3": "Interlocuteur",
    "4": "Intervenant",
    "5": "Temporaire",
    "6": "Bénéficiaire présumé",
    "7": "Autre",
}

MOTIF_FT = {
    "1": "Retour enquêteur négatif",
    "2": "GDP sans suite",
    "3": "Problème juridique",
    "4": "Dévolution non transmise",
    "5": "Succession vacante",
    "6": "Reprise d'antériorité",
    "7": "Mise en perte/profit",
    "8": "Séralys LBPP",
    "9": "Autre",
    "10": "Retour généalogiste négatif"
}

MOTIF_ATTENTE = {
    '1': 'Action judiciaire CNP',
    '2': 'Contentieux externe',
    '3': 'Séralys LBPP',
    '4': 'Généalogiste CNP en cours',
    '5': 'Transfert manuel CDC'
}

INTERLOCUTEUR = {
    "1": "Conseiller financier",
    "2": "CRSF",
    "3": "Notaire",
    "4": "Proche",
    "5": "Pompes funèbres",
    "6": "Maison de retraite",
    "7": "Services fiscaux",
    "8": "Association",
    "9": "Organisme bancaire",
    "10": "Caisse d'épargne",
    "11": "Bénéficiaire",
    "12": "Conseiller CNP Trésor",
    "13": "Mairie",
    "14": "Généalogiste",
    "15": "Enquêteur",
    "16": "CNAH",
    "17": "OGF",
    "18": "Le Choix Funéraire",
    "19": "CNP ASSURANCES",
    "20": "SIE",
    "21": "Caisse des Dépôts et Consignations",
    "22": "AGIRA",
    "23": "Fondation",
    "24": "La Banque Postale Prévoyance",
    "25": "Etat",
    "26": "SPFE SDE",
    "99": "Autre"
}


#: Tables indexed by the name exposed to the model (tool ``libelle_nomenclature``).
NOMENCLATURES: dict[str, dict[str, str]] = {
    "type_evenement": TYPE_EVT,
    "sous_type_evenement": SOUS_TYPE_EVT,
    "sous_type_alerte": SOUS_TYPE_ALERTE,
    "type_intercalaire": TYPE_INTERCALAIRE,
    "motif_fin_traitement": MOTIF_FT,
    "motif_attente": MOTIF_ATTENTE,
    "interlocuteur": INTERLOCUTEUR,
}
